spyder_terminal/__init__.py, spyder_terminal/server/logic/term_manager.py, spyder_terminal/server/main.py, spyder_terminal/server/static/css/style.css, spyder_terminal/server/static/js/main.js, spyder_terminal/terminalplugin.py
=> Spyder IDE integration

MANIFEST.in, setup.py, spyder_terminal/terminalplugin.py
=> Server now starts and stops with Spyder process

circle.yml, setup.py, spyder_terminal/server/static/css/style.css, spyder_terminal/server/static/js/main.js, spyder_terminal/terminalplugin.py, spyder_terminal/widgets/terminalgui.py
=> PR: Added basic shortcuts and menu entries

spyder_terminal/server/main.py, spyder_terminal/widgets/terminalgui.py
Server executes by default on port 8070
=> PR: Server deploys on port 8070 by default

.ciocheck, .coveragerc, circle.yml, runtests.py, spyder_terminal/terminalplugin.py, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
=> PR: Basic test added

bower.json, spyder_terminal/server/static/css/style.css, spyder_terminal/server/static/index.html, spyder_terminal/server/static/js/main.js, spyder_terminal/widgets/terminalgui.py
=> Overflow resolution

spyder_terminal/server/static/css/style.css, spyder_terminal/server/static/js/main.js, spyder_terminal/terminalplugin.py, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
=> PR: Custom font loading

spyder_terminal/__init__.py, spyder_terminal/tests/test_terminal.py
=> Plugin import is restricted to PyQt5

spyder_terminal/terminalplugin.py, spyder_terminal/tests/test_terminal.py
=> Terminal tabs naming convention is sequential

spyder_terminal/server/main.py, spyder_terminal/terminalplugin.py, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
=> Server port is now variable

spyder_terminal/server/static/js/main.js, spyder_terminal/terminalplugin.py, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
=> New terminals inherit Spyder current working directory

spyder_terminal/__init__.py, spyder_terminal/widgets/terminalgui.py
=> PR: Removed reference to contentsChanged signal

spyder_terminal/terminalplugin.py
=> PR: Update plugin name to Terminal

spyder_terminal/server/static/js/main.js, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
Restore resizing behaviour via Javascript instead of doing it via Qt
=> PR: Update font size and geometry after terminal has finished loading

spyder_terminal/server/static/css/style.css, spyder_terminal/server/static/js/main.js, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
=> PR: Fixed scroller issues

CHANGELOG.md, README.md, setup.py
=> PR: Added release v0.1.1 notes

spyder_terminal/terminalplugin.py, spyder_terminal/widgets/terminalgui.py
=> PR: Make the terminal to capture all keyboard events

CHANGELOG.md, CHANGELOG.temp, spyder_terminal/__init__.py
=> Release v0.1.2

spyder_terminal/__init__.py, spyder_terminal/terminalplugin.py
=> PR: Add plugin check_compatibility

spyder_terminal/terminalplugin.py
=> PR: Tabify terminal next to the IPython Console

circle.yml, requirements.txt, setup.py
=> PR: Version 0.2 should depend on Spyder 3.2

spyder_terminal/server/static/js/main.js
=> Emit initialization commands only if prompt is ready

MANIFEST.in, spyder_terminal/terminalplugin.py, spyder_terminal/widgets/terminalgui.py
=> PR: Copy and Paste shortcuts update

appveyor.yml, circle.yml, spyder_terminal/server/main.py, spyder_terminal/server/rest/term_rest.py, spyder_terminal/server/routes.py, spyder_terminal/server/tests/__init__.py, spyder_terminal/server/tests/print_size.py, spyder_terminal/server/tests/test_server.py, spyder_terminal/server/websockets/term_ws.py
=> PR: Add server tests

setup.py, spyder_terminal/server/logic/term_manager.py
Fixes #90 
It also updates pywinpty dependency to version 0.1.2
=> PR: Close websocket if process was stopped on Windows

appveyor.yml, spyder_terminal/server/logic/term_manager.py, spyder_terminal/server/rest/term_rest.py, spyder_terminal/server/static/js/main.js, spyder_terminal/server/web/main_handler.py, spyder_terminal/server/websockets/term_ws.py, spyder_terminal/widgets/terminalgui.py
=> PR: Simplify initialization routine

spyder_terminal/terminalplugin.py, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
=> PR: Reduce test execution times

.gitignore, appveyor.yml, spyder_terminal/terminalplugin.py
=> PR: Remove Windows/Py2.7 restriction

spyder_terminal/terminalplugin.py
=> PR: Add winpty import verification before starting plugin

README.rst
@ccordoba12 Per the discussion in spyder-ide/spyder#7262 , this PR updates the readme with an up to date funding status message, and also harmonizes it with the layout and format of the main readme and fixes a few obvious bugs/typos in the text. You can preview the full changes live over on [my repo](https://github.com/CAM-Gerlach/spyder-terminal/blob/update-funding-message/README.rst).
Once the changes are agreed upon and approved, I'll go ahead and push the same modifications to the other Spyder plugins (other than ``spyder-unittest``).
=> PR: Update funding message, harmonize with main Spyder readme and minor fixes

spyder_terminal/terminalplugin.py
=> PR: Update SpyderPluginWidget import 

package-lock.json, package.json, setupbase.py, spyder_terminal/server/static/js/main.js, yarn.lock
- Upgrade xtermjs from 3.15.4 to 4.2
- Add the search functionality on the server
=> PR: Upgrade xterm to 4.2 and add search functionality

README.rst, setup.py
The Readme needed some love before the final release.
=> PR: Make some improvements to the Readme

package-lock.json, package.json, requirements/conda.txt, requirements/conda_win.txt, yarn.lock
Upgrade the terminal to 4.4.0 version and pin dependencies for release
=> PR: Update to latest xterm.js version and pin dependencies

CHANGELOG.md, RELEASE.md, spyder_terminal/__init__.py
I had to open this PR because of the write protection check to master
=> Release version 0.3.0

.circleci/config.yml, azure-pipelines.yml, continuous_integration/azure/install.sh, continuous_integration/circle/install.sh, continuous_integration/circle/runtests.sh, package-lock.json, package.json, spyder_terminal/server/tests/test_server.py, yarn.lock
- The deprecated dependencies are updated
- Python 2 is removed from the CI
=> PR: Update deprecated dependencies and remove Python 2 from CIs

spyder_terminal/server/tests/test_server.py
as promised, my take to fix #179
Fixes #179
=> PR: Use sys.executable in test_terminal_resize

.circleci/config.yml, azure-pipelines.yml, conftest.py
=> PR: Add conftest.py and remove the SPYDER_DEV variable in the CIs

MANIFEST.in, setup.py
=> PR: Exclude tests from distribution package

spyder_terminal/tests/test_terminal.py
=> PR: Do not set DEV but assert it has been set

spyder_terminal/server/static/js/main.js, spyder_terminal/widgets/terminalgui.py
Removes the bug of small and weird font in terminal resize
=> PR: Fix font size bug when resizing the terminal

package-lock.json, package.json, yarn.lock
Upgrade to latest xtermjs release
Fixes #213
=> PR: Upgrade xterm to 4.7 release

spyder_terminal/server/static/js/main.js, spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/terminalgui.py
Improves the paste mechanism in the terminal and fixes an unused class herarchy
=> PR: Improve clipboard support in the terminal

spyder_terminal/locale/de/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/es/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/fr/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/hu/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/ja/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/pl/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/pt_BR/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/ru/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/spyder_terminal.pot, spyder_terminal/locale/zh_CN/LC_MESSAGES/spyder_terminal.po
Update translation files with new strings before release
=> PR: Update translation files

spyder_terminal/server/__main__.py
This change fixes #235 adding the recommended patch from the latest tornado release
=> PR: Add tornado patch for python 3.8 in windows

spyder_terminal/confpage.py
=> PR: Add Xonsh to list of supported terminals in Unix and Windows

README.rst, azure-pipelines.yml, continuous_integration/azure/install.bat, requirements/conda.txt, requirements/conda_win.txt, setup.py, spyder_terminal/server/logic/term_manager.py
This changes include the fix of the changes made in https://github.com/jupyter/terminado/pull/76
Fixes #242
Fixes #240
=> PR: Fix new terminal with work with latest Terminado version

package-lock.json, package.json, yarn.lock
This PR upgrades to the latest version of xtermjs
=> PR: Upgrade to xtermjs 4.13.0

README.rst
This is needed for spyder-ide/spyder#15907.
=> PR: Add note to Readme to mention that this plugin doesn't work with our installers

spyder_terminal/tests/test_terminal.py, spyder_terminal/widgets/main_widget.py, spyder_terminal/widgets/terminalgui.py
This PR adds conda support to the terminal,
It was tested on all platforms and running Spyder without the development mode.
Fixes #164 
Fixes #250
=> PR: Source terminal config files to have conda in PATH

requirements/conda.txt, requirements/conda_win.txt, setup.py, spyder_terminal/widgets/main_widget.py
=> PR: Pin new version of Spyder and Pywinpty

spyder_terminal/locale/de/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/es/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/fr/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/hr/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/hu/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/ja/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/pl/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/pt_BR/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/ru/LC_MESSAGES/spyder_terminal.po, spyder_terminal/locale/spyder_terminal.pot, spyder_terminal/locale/zh_CN/LC_MESSAGES/spyder_terminal.po
Update translations for new release
=> PR: Update translations for Spyder 1.0.0 release

requirements/conda.txt, requirements/conda_win.txt, setup.py, spyder_terminal/terminalplugin.py
=> PR: Migrate registry to the new Spyder 5.1 API

spyder_terminal/widgets/main_widget.py
This PR opens new terminals in the project path, if active
=> PR: Open new terminals in the project path if active

setup.py
- This was missing from #293.
- I also missed it in my review, sorry.
- I'll fix this in our conda-forge packages fo now, but it requires a new release to fix it in PyPI.
=> PR: Increase minimal Spyder version in setup.py

.circleci/config.yml, azure-pipelines.yml, continuous_integration/azure/install.sh, continuous_integration/circle/install.sh, requirements/conda.txt, requirements/conda_win.txt, setup.py
=> PR: Update CIs

spyder_terminal/server/logic/term_manager.py, spyder_terminal/widgets/terminalgui.py
* Updated shell startup files for bash and zsh to reflect interactive login
* Removed environment variables from the shell environment that were introduced by Spyder
=> PR: Update plugin to be compatible with Spyder macOS installer
