spyder_terminal/server/logic/term_manager.py

Console manager constructor was failing on Windows due to a reference call to the class ``pexpect.spawnu``, which is inexistent on this OS

PR: Modified pexpect constructor orden between OSes

---

spyder_terminal/server/logic/term_manager.py
spyder_terminal/server/main.py
spyder_terminal/terminalplugin.py

With this we assure the server is running with the same Python as the one used by Spyder.

PR: Use sys.executable to start the server

---

spyder_terminal/server/static/js/main.js

PR: Added Content-Type header to all HTTP requests

---

spyder_terminal/terminalplugin.py
spyder_terminal/widgets/terminalgui.py

Fixes #45 
Now is possible to open terminals at the following locations:
* Current workspace folder
* Project folder (If present)
* Current opened file at editor

PR: Added more options for opening terminals at different locations

---

.gitignore
spyder_terminal/__init__.py
spyder_terminal/terminalplugin.py
spyder_terminal/tests/test_terminal.py

PR: Redirecting server stderr and stdout to files

---

requirements.txt
setup.py
spyder_terminal/server/static/js/main.js
spyder_terminal/terminalplugin.py
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

PR: Launch first console instance only if server is up

---

MANIFEST.in
RELEASE.md
setup.cfg
setup.py
setupbase.py
spyder_terminal/__init__.py
spyder_terminal/terminalplugin.py

Fixes #85 
----
@andfoy, please take a close look at the release instructions in RELEASE.md:
1. I added a command called `clean_components` to clean server JS components before building a new release.
2. With my additions you can build the Windows wheels on Linux (or any other platform :-). But you need to use the commands I posted in RELEASE.md for that.
3. We can build a single universal wheel for Mac and Linux. The good thing about pip is that it tries to install OS specific wheels first and then the universal ones.
4. I verified that with these fixes we can create conda packages. The previous versions can't be built with conda-build because you forgot to add setupbase.py to the gzip tarballs.

PR: Several installation fixes

---

spyder_terminal/terminalplugin.py

This was making the plugin to gain focus during Spyder startup, which was driving me crazy.

PR: Don't raise plugin when a new terminal is created

---

spyder_terminal/server/static/js/main.js
spyder_terminal/server/tests/test_server.py
spyder_terminal/terminalplugin.py
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

PR: Close terminal tab if process was closed

---

circle.yml
spyder_terminal/server/static/index.html
spyder_terminal/server/static/js/main.js
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

PR: QWebChannel implementation and tests

---

spyder_terminal/widgets/terminalgui.py

PR: Do not clean WebEngine cache when using WebKit

---

appveyor.yml
circle.yml
spyder_terminal/tests/test_terminal.py

@andfoy, I had to pin `pyqt=5.6*` in Circle because there were too many tests failing with PyQt 5.9. However, we're testing with 5.9 on Windows.

PR: Fix running tests in CI infrastructure

---

README.rst
appveyor.yml
setup.py

PR: Remove pexpect from windows requirements

---

spyder_terminal/config.py
spyder_terminal/terminalplugin.py
spyder_terminal/widgets/terminalgui.py

With these changes we are able to configure dynamically the shortcuts in the terminal.
They can be changed on the preferences
**Copy**
**New term**
**Paste**

PR: Add shortcuts configuration

---

spyder_terminal/server/static/css/style.css
spyder_terminal/terminalplugin.py

These changes allow the plugin to have a consistent UI with the rest of spyder. The buttons and the menu have the same options.
Fixes #161

PR: Fix styling issues for UI consistency

---

spyder_terminal/server/static/css/style.css

With this minor change the double bar doesn't appear in the terminal in Linux

PR: Fix double scroll bar appearing in Linux

---

spyder_terminal/confpage.py

Taking into account that the default terminal for Catalina is `zsh`, change the default option for macOS to `zsh`.
We are not able to get the login shell correctly using `echo $SHELL` or equivalent methods on the terminal because they are not reliable as seen in the following image.
Fixes #177

PR: Change default terminal for macOS Catalina

---

RELEASE.md

@steff456, this is the new way to generate our Changelog with Zenhub.
You also need to create a file called `~/.loghubrc` with the following content:
```ini
[github]
token = 
[zenhub]
token = 
```
For the Github part, you need to create a [personal access token](https://github.com/settings/tokens) and add it to it. For the Zenhub part, I'll send you the token privately.

PR: Update release instructions with new loghub command

---

README.rst
package.json
spyder_terminal/server/static/js/main.js

Fix the change in the API of the buffer created in xterm 4.5.0 version

PR: Add compatibility with the latest release of xterm

---

spyder_terminal/confpage.py

The confpage is missing an import and is thus not displayed in the spyder settings.
```
File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3175, in show_preferences
widget = plugin._create_configwidget(dlg, self)
File "/usr/lib/python3.8/site-packages/spyder/plugins/base.py", line 117, in _create_configwidget
configwidget.initialize()
File "/usr/lib/python3.8/site-packages/spyder/preferences/configdialog.py", line 72, in initialize
self.load_from_conf()
File "/usr/lib/python3.8/site-packages/spyder/preferences/configdialog.py", line 327, in load_from_conf
checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
Traceback (most recent call last):
File …
```

PR: Import sys for confpage

---

spyder_terminal/server/logic/term_manager.py
spyder_terminal/server/tests/test_server.py
spyder_terminal/terminalplugin.py
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

Remove compatibility with python 2
Fixes #212

PR: Move Spyder-terminal plugin to Python 3

---

spyder_terminal/server/static/js/main.js
spyder_terminal/tests/test_terminal.py

Update the selection theme color in rgba format instead of hex. In this way the transparency is added to the themes.
Fixes #202 
Idle
Spyder
Spyder Dark
Pastel

PR: Fix highlight text on the terminal

---

spyder_terminal/config.py
spyder_terminal/server/static/js/main.js
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

Now the user can zoom in or zoom out of the terminal with `Ctrl++` and `Ctrl+-` shortcuts
Fixes #148

PR: Add option to zoom in/zoom out in the terminal

---

spyder_terminal/config.py
spyder_terminal/terminalplugin.py
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

The shortcuts are visible again in the Preferences pane for the user to change the key combinations
Fixes #218

PR: Fix shortcuts to new API

---

spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

This code is deprecated by Qt5
Fixes #219

PR: Remove deprecated QWebKit code

---

spyder_terminal/server/static/js/main.js
spyder_terminal/terminalplugin.py
spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/findwidget.py
spyder_terminal/widgets/terminalgui.py

Add the widget for finding text in the terminal
Now the terminal is able to find with all the options of the rest of the panes in Spyder
Fixes #224

PR: Add find widget to the terminal

---

spyder_terminal/config.py
spyder_terminal/confpage.py
spyder_terminal/widgets/terminalgui.py

This option allows the user to define the number of buffer lines in the terminal
Fixes #227

PR: Add scrollback option to the terminal

---

spyder_terminal/server/logic/term_manager.py
spyder_terminal/server/web/main_handler.py
spyder_terminal/tests/test_terminal.py

Adds support to paths that have special characters.
Fixes #225

PR: Percent encode/decode cwd to encode spaces and special characters

---

package-lock.json
package.json
requirements/conda.txt
yarn.lock

Upgrade to xtermjs 4.9.0 and Spyder 4.2
Resolves the security problem with `node-forge`

PR: Upgrade dependencies of xtermjs and Spyder

---

spyder_terminal/config.py
spyder_terminal/confpage.py
spyder_terminal/widgets/terminalgui.py

This PR adds two features:
- Add the capability to enable/disable the cursor to blink
- Saves the zoom used by the user and it is used by default when opening new terminals
zoom out:
zoom in:
Fixes #247

PR: Add new cursor option and zoom to the terminal

---

spyder_terminal/widgets/main_widget.py
spyder_terminal/widgets/terminalgui.py

This PR adds a blue border when the widget is focused,
Focused:
Not Focused:
Note: I was unable to use Spyder's `FrameWebView ` class because the WebView and QFrame of spyder-terminal diverge greatly from that implementation.

PR: Add blue border when the terminal is focused

---

.circleci/config.yml
azure-pipelines.yml
requirements/conda.txt
requirements/conda_win.txt
spyder_terminal/terminalplugin.py

This PR updates to Spyder 5.2.x API,

PR: Update to Spyder 5.2.x API

---

package-lock.json
package.json
spyder_terminal/server/static/js/main.js
yarn.lock

PR: Update to xterm 4.15

---

README.rst

- It's not possible to install Spyder-terminal from our own channel (even if we copy the conda-forge packages to it), so we need to tell people to create a new environment with conda-forge instead.
- See for instance the following issue for an example of the current behavior: #288

PR: Update installation instructions for conda

---

spyder_terminal/tests/test_terminal.py
spyder_terminal/widgets/terminalgui.py

This PR avoids double decreasing/increasing zoom when a new terminal is created
Fixes #302

PR: Fix double zoom when openning a new terminal

---

requirements/conda_win.txt

The latest pywinpty release fixes some issues with terminado console termination as well CI issues that arose when `windows-2019` was used.

PR: Update pywinpty version to v2.0.5
